version: "3.1"

services:
  api_gateway:
    container_name: api_gateway
    hostname: api_gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
      - "443:443"
    networks:
      - network

  accommodation_service:
    build:
      context: ./accommodation/
      dockerfile: Dockerfile
    restart: always
    container_name: "accommodation_service"
    hostname: "accommodation_service"
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_DB_URI=${MONGO_DB_URI_ACCOMMODATION}
      - PROFILE_SERVICE_URI=${PROFILE_SERVICE}
      - RESERVATION_SERVICE_URI=${RESERVATION_SERVICE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HDFS_URI=namenode:9000
    depends_on:
      accommodation_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      namenode:
        condition: service_healthy
      datanode1:
        condition: service_healthy
    volumes:
      - acco_logs:/logger
    networks:
      - network

  accommodation_db:
    hostname: "accommodation_db"
    container_name: "accommodation_db"
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: accommodationDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - accommodation_db:/data/db
    networks:
      - network
  
  redis:
    container_name: "redis"
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - network
  
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=stayinn
    env_file:
      - ./hdfs.env
    networks:
      - network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hdfs.env
    networks:
      - network

  auth_service:
    build:
      context: ./auth/
      dockerfile: Dockerfile
    restart: always
    container_name: "auth_service"
    hostname: "auth_service"
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - MONGO_DB_URI=${MONGO_DB_URI_AUTH}
      - PROFILE_SERVICE_URI=${PROFILE_SERVICE}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      auth_db:
        condition: service_healthy
    volumes:
      - auth_logs:/logger
    networks:
      - network

  auth_db:
    hostname: "auth_db"
    container_name: "auth_db"
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: authDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - auth_db:/data/db
    networks:
      - network

  reservation_service:
    build:
      context: ./reservation/
      dockerfile: Dockerfile
    restart: always
    container_name: "reservation_service"
    hostname: "reservation_service"
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - CASS_DB=${CASS_DB}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - ACCOMMODATION_SERVICE_URI=${ACCOMMODATION_SERVICE}
      - PROFILE_SERVICE_URI=${PROFILE_SERVICE}
      - NOTIFICATION_SERVICE_URI=${NOTIFICATION_SERVICE}
    depends_on:
      reservation_db:
        condition: service_healthy
    volumes:
      - rese_logs:/logger
    networks:
      - network

  reservation_db:
    hostname: "reservation_db"
    container_name: "reservation_db"
    image: cassandra
    restart: always
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 15s
      timeout: 5s
      retries: 15
    volumes:
      - cass_store:/var/lib/cassandra/data
    networks:
      - network

  profile_service:
    build:
      context: ./profile/
      dockerfile: Dockerfile
    restart: always
    container_name: "profile_service"
    hostname: "profile_service"
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - MONGO_DB_URI=${MONGO_DB_URI_PROFILE}
      - AUTH_SERVICE_URI=${AUTH_SERVICE}
      - ACCOMMODATION_SERVICE_URI=${ACCOMMODATION_SERVICE}
      - RESERVATION_SERVICE_URI=${RESERVATION_SERVICE}
    depends_on:
      profile_db:
        condition: service_healthy
    volumes:
      - prof_logs:/logger
    networks:
      - network

  profile_db:
    hostname: "profile_db"
    container_name: "profile_db"
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: profileDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - profile_db:/data/db
    networks:
      - network

  notification_service:
    build:
      context: ./notification/
      dockerfile: Dockerfile
    restart: always
    container_name: "notification_service"
    hostname: "notification_service"
    ports:
      - 8084:8084
    environment:
      - PORT=8084
      - MONGO_DB_URI=${MONGO_DB_URI_NOTIFICATION}
      - PROFILE_SERVICE_URI=${PROFILE_SERVICE}
      - RESERVATION_SERVICE_URI=${RESERVATION_SERVICE}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      notification_db:
        condition: service_healthy
    volumes:
      - noti_logs:/logger
    networks:
      - network

  notification_db:
    hostname: "notification_db"
    container_name: "notification_db"
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: notificationDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - notification_db:/data/db
    networks:
      - network

volumes:
  accommodation_db:
  redis_data:
  hadoop_namenode:
  hadoop_datanode1:
  auth_db:
  cass_store:
  profile_db:
  notification_db:
  acco_logs:
  auth_logs:
  noti_logs:
  prof_logs:
  rese_logs:

networks:
  network:
    driver: bridge
