version: "3.1"

services:
  accommodation:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "accommodation-service"
    hostname: "accommodation-service"
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - CASS_DB=cassandra:9042
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=root
      - CASSANDRA_PASSWORD=pass
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra:
    image: cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cass_store:/var/lib/cassandra/data
    environment:
      - CASSANDRA_USER=root
      - CASSANDRA_PASSWORD=pass
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 15s
      timeout: 5s
      retries: 15


volumes:
  cass_store:

